# Generated by Django 4.2.2 on 2023-06-29 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50)),
                ('experience', models.BooleanField(default=False)),
                ('position', models.CharField(max_length=20)),
                ('goals', models.CharField(blank=True, max_length=500, null=True)),
                ('date', models.DateField(verbose_name='lesson date')),
            ],
        ),
    ]
