# Generated by Django 4.2.2 on 2023-06-29 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='goals',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
